spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://112.221.66.174:3308/climbdb
        username: gangnam
        password: gangnam
mybatis:
    mapper-locations: mapper/*.xml
